MiblogBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MiblogBundle:Default:index }

articles:
  pattern:  /articles
  defaults: { _controller: MiblogBundle:Article:index }

article:
  pattern: /article/{slug}
  defaults: { _controller: MiblogBundle:Article:article }
  
articles_id:
  pattern: /article/id/{id}
  defaults: { _controller: MiblogBundle:Article:articleid }
  
