parameters:
#    miblog.example.class: Miblog\MiblogBundle\Example

services:
#    miblog.example:
#        class: %miblog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
