<?php

namespace Miblog\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRespository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRespository extends EntityRepository
{
}